package sink.task;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.kafka.connect.sink.SinkRecord;
import org.apache.kafka.connect.sink.SinkTask;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import sink.connector.HexGraphSinkConnector;

import java.io.*;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.Map;
import java.util.Optional;

import static sink.config.HexGraphSinkConnectorConfig.DIRECTORY_SINK;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jack' at '8/01/18 3:30 PM' with Gradle 2.10
 *
 * @author jack, @date 8/01/18 3:30 PM
 */
public class HexGraphSinkTask extends SinkTask {
    public static final Logger LOGGER = LoggerFactory.getLogger(HexGraphSinkTask.class);

    private String directorySink;

    @Override
    public String version() {
        return new HexGraphSinkConnector().version();
    }

    @Override
    public void start(Map<String, String> props) {
        LOGGER.info("Hex graph sink task starting.");

        directorySink = props.get(DIRECTORY_SINK);

        File directory = new File(directorySink);
        if (!directory.exists()) {
            directory.mkdir();
        }
    }

    @Override
    public void put(Collection<SinkRecord> records) {
        LOGGER.info("$$$$$$$$$ PUTTING $$$$$$$$$$$$$$");
        try {
            ObjectMapper objectMapper = new ObjectMapper();

            for (SinkRecord sinkRecord : records) {
                LOGGER.info("!!!!!!!!!!!!!!");

                HexGraphResult hexGraphResult = objectMapper.readValue(objectMapper.writeValueAsString(sinkRecord.value()),
                        HexGraphResult.class);

                String creationDate = Optional.of(hexGraphResult.getCreationDate()).orElse(LocalDateTime.now().toString());
                String imagePath = hexGraphResult.getImagePath();

                String fileName = directorySink + "/" + creationDate;

                HexGraphFileContent hexGraphFileContent = new HexGraphFileContent(imagePath, hexGraphResult.getCounts());

                LOGGER.info(fileName + "::::: " + hexGraphFileContent.toString());
                FileOutputStream fos = new FileOutputStream(fileName);
                DataOutputStream outStream = new DataOutputStream(new BufferedOutputStream(fos));
                outStream.writeUTF(objectMapper.writeValueAsString(hexGraphFileContent));
                outStream.close();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void stop() {
        LOGGER.info("Hex graph sink task stopping.");
    }
}
